todoproject/todoproject/todoapp/urls.py
from . import views
from django.urls import path

app_name = 'todoapp'
urlpatterns = [

    path('', views.add, name='add'),
    path('delete/<int:taskid>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('cbvhome/',views.TaskListview.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailview.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.TaskUpdateview.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskDeleteview.as_view(), name='cbvdelete'),

]

todoproject/todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject/todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
       return self.name

todoproject/todoproject/todoapp/forms.py
from .models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name', 'priority', 'date']

todoproject/todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import TodoForm
from . models import Task
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


# Create your views here.
class TaskListview(ListView):
    model=Task
    template_name='home.html'
    context_object_name='task1'

class TaskDetailview(DetailView):
    model=Task
    template_name='detail.html'
    context_object_name='task1'

class TaskUpdateview(UpdateView):
    model=Task
    template_name='update.html'
    context_object_name='task1'
    fields=('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})

class TaskDeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvhome')

def add(request):
    task1=Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task', '')
        priority=request.POST.get('priority', '')
        date=request.POST.get('date','')
        task=Task(name=name, priority=priority, date=date)
        task.save()
    return render(request, 'home.html',{'task1':task1})

# def details(request):
#     return render(request,'detail.html')

def delete(request, taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
            task.delete()
            return redirect('/')
    return render(request, 'delete.html')

def update(request, id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request, 'edit.html', {'f':f,'task':task})

todoproject/todoproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject/todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <p><b>Are you sure this task is done?</b></p>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproject/todoproject/templates/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="shadow card">
    <div class="card-body">
        <h5 class="card-title">Name:{{task1.name}}</h5>
        <p><b>Priority:{{task1.priority}}</b></p>
        <p><b>Date:{{task1.date}}</b></p>
        <a class="btn btn-danger" href="{% url 'todoapp:delete' task1.id %}">Done</a>
        <a class="btn btn-primary" href="{% url 'todoapp:update' task1.id %}">Update</a>
    </div>
</div>

{% endblock %}

todoproject/todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">Confirm</button>
</form>
{% endblock %}

todoproject/todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>To Do Tasks</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow" style="background-color:red;">
                {% csrf_token %}
                <div class="form-group">
                 <input type="text" name="task" class="form-control" placeholder="Task name">
                </div>
                <div class="form-group">
                 <input type="text" name="priority" class="form-control" placeholder="Enter your priority">
                </div>
                 <div class="form-group">
                 <input type="date" name="date" class="form-control" placeholder="Enter the date">
                </div>
                 <input type="submit" class="btn btn-success">
            </form>
        </div>
        <div class="col-md-6">
            <h3 style="color:blue;background-color:pink;">Task to be completed</h3>
            {% for i in task1 %}
             <div class="shadow card">
                 <div class="card-body">
                     <h5 class="card-title">Name:{{i.name}}</h5>
                     <p><b>Priority:{{i.priority}}</b></p>
                     <p><b>Date:{{i.date}}</b></p>
                     <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                     <a class="btn btn-primary" href="{% url 'todoapp:update' i.id %}">Update</a>
                 </div>
             </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

todoproject/todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
   <div class="card-header">
      <div class="card-title">
        Task update
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit">Submit</button>
        </form>
      </div>
   </div>
</div>
{% endblock %}